/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Personas */
        get: operations["list_personas_personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Query */
        post: operations["run_query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Participants */
        get: operations["participants_participants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participants/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Participant */
        get: operations["participant_participants__person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participants/{person_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain */
        get: operations["explain_participants__person_id__explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participants/{person_id}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_participants__person_id__compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cohort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cohort */
        get: operations["cohort_cohort_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clock State */
        get: operations["clock_state_clock_get"];
        put?: never;
        /** Control Clock */
        post: operations["control_clock_clock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description Push a `tick` whenever the clock moves or the live readings change.
         *
         *     Each tick carries the newly visible windows and everyone visible's live
         *     readings. `reset` is true when the clock jumped backwards (a seek): the UI
         *     should re-run its queries rather than append.
         */
        get: operations["stream_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Turn */
        post: operations["chat_turn_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Threads */
        get: operations["threads_chat_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thread */
        get: operations["thread_chat_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tools
         * @description The tools the caller's chatbot can use, with their JSON schemas.
         */
        get: operations["tools_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Widgets */
        get: operations["list_widgets_widgets_get"];
        put?: never;
        /** Pin Widget */
        post: operations["pin_widget_widgets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widgets/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Widget
         * @description Rebuild a widget from its spec without pinning it (keeps chat widgets live).
         */
        post: operations["preview_widget_widgets_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widgets/{widget_id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Widget Data */
        get: operations["widget_data_widgets__widget_id__data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widgets/{widget_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unpin Widget */
        delete: operations["unpin_widget_widgets__widget_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Catalog */
        Catalog: {
            /** As Of */
            as_of: string | null;
            /** Data Start */
            data_start: string | null;
            /** Data End */
            data_end: string | null;
            /** Metrics */
            metrics: components["schemas"]["MetricInfo"][];
            /** Participants */
            participants: components["schemas"]["ParticipantInfo"][];
            /** Buckets */
            buckets: string[];
            /** Aggs */
            aggs: string[];
            /** Group Bys */
            group_bys: string[];
        };
        /** ChangeReport */
        ChangeReport: {
            /** Person Id */
            person_id: string;
            /** Display Name */
            display_name: string;
            /** As Of */
            as_of: string | null;
            /** Hours */
            hours: number;
            /**
             * Now Window End
             * Format: date-time
             */
            now_window_end: string;
            /** Then Window End */
            then_window_end: string | null;
            /** Changes */
            changes: components["schemas"]["MetricChange"][];
            /** Largest Shifts */
            largest_shifts: string[];
            /**
             * Note
             * @default Changes compare the most recent 24 h window with the one N hours earlier; standard deviation (SD) scores compare the latest value with this patient's own last 7 days. These are associations, not causal relationships, and the Gluco Score is a model estimate, not a measurement or a diagnosis.
             */
            note?: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Role */
            role: string;
            /** Text */
            text: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Session Id */
            session_id: string;
            /** Message */
            message: string;
        };
        /** ChatThread */
        ChatThread: {
            /** Session Id */
            session_id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ClockCommand */
        ClockCommand: {
            /**
             * Action
             * @enum {string}
             */
            action: "play" | "pause" | "speed" | "seek";
            /** Seconds Per Hour */
            seconds_per_hour?: number | null;
            /** To */
            to?: string | null;
        };
        /** ClockState */
        ClockState: {
            /** Now */
            now: string | null;
            /** Playing */
            playing: boolean;
            /** Seconds Per Hour */
            seconds_per_hour: number;
            /** Enabled */
            enabled: boolean;
            /** Data Start */
            data_start: string | null;
            /** Data End */
            data_end: string | null;
            /** At End */
            at_end: boolean;
        };
        /** CohortComparison */
        CohortComparison: {
            /** Person Id */
            person_id: string;
            /** Metric */
            metric: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
            /** Cohort Median */
            cohort_median: number;
            /** Cohort Mean */
            cohort_mean: number;
            /** Z Score */
            z_score: number;
            /** Percentile */
            percentile: number;
            /** Direction */
            direction: string;
            /** Cohort Size */
            cohort_size: number;
            /**
             * Percentile Method
             * @default normal_approximation
             */
            percentile_method?: string;
        };
        /** CohortOverview */
        CohortOverview: {
            /** As Of */
            as_of: string | null;
            /** Participants */
            participants: number;
            gluco_score: components["schemas"]["MetricSummary"] | null;
            /** Lowest Gluco */
            lowest_gluco: components["schemas"]["ParticipantRow"][];
            /** Biggest Drops */
            biggest_drops: components["schemas"]["ParticipantRow"][];
            /** Biggest Gains */
            biggest_gains: components["schemas"]["ParticipantRow"][];
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["MetricSummary"];
            };
        };
        /** ExplainResponse */
        ExplainResponse: {
            change: components["schemas"]["ChangeReport"];
            /** Cohort Position */
            cohort_position: components["schemas"]["FeatureDeviation"][] | null;
        };
        /** FeatureDeviation */
        FeatureDeviation: {
            /** Feature */
            feature: string;
            /** Value */
            value: number;
            /** Median */
            median: number;
            /** Z Score */
            z_score: number;
            /** Percentile */
            percentile: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "above" | "below" | "at";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Db */
            db: boolean;
            /** Llm */
            llm: boolean;
            /** Windows */
            windows: number;
            /** Participants */
            participants: number;
            clock: components["schemas"]["ClockState"] | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Persona Id */
            persona_id: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Token */
            token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type?: "bearer";
            /** Expires In */
            expires_in: number;
            principal: components["schemas"]["PrincipalOut"];
        };
        /** MetricChange */
        MetricChange: {
            /** Metric */
            metric: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Now */
            now: number | null;
            /** Then */
            then: number | null;
            /** Delta */
            delta: number | null;
            /** Baseline Mean */
            baseline_mean: number | null;
            /** Z Vs Baseline */
            z_vs_baseline: number | null;
        };
        /** MetricInfo */
        MetricInfo: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Description */
            description: string;
            /** Higher Is Better */
            higher_is_better: boolean | null;
            /** Live */
            live: boolean;
        };
        /** MetricSummary */
        MetricSummary: {
            /** Mean */
            mean: number;
            /** Median */
            median: number;
            /** Stddev */
            stddev: number;
            /** Min */
            min: number;
            /** Max */
            max: number;
            /** N */
            n: number;
        };
        /** ParticipantInfo */
        ParticipantInfo: {
            /** Person Id */
            person_id: string;
            /** Display Name */
            display_name: string;
            /** Source Dataset */
            source_dataset: string;
        };
        /** ParticipantRow */
        ParticipantRow: {
            /** Person Id */
            person_id: string;
            /** Display Name */
            display_name: string;
            /** Source Dataset */
            source_dataset: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /** Values */
            values: {
                [key: string]: number | null;
            };
            /** Live At */
            live_at?: string | null;
        };
        /** PinnedWidget */
        PinnedWidget: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "trend" | "ranking" | "cohort_trend" | "stat" | "table" | "heatmap";
            query: components["schemas"]["QuerySpec"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PrincipalOut */
        PrincipalOut: {
            /** User Id */
            user_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "clinician" | "patient";
            /** Display Name */
            display_name: string;
            /** Participant Id */
            participant_id: string | null;
        };
        /** QueryResult */
        QueryResult: {
            /** As Of */
            as_of: string | null;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Metrics */
            metrics: string[];
            /** Units */
            units: {
                [key: string]: string;
            };
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "raw" | "hour" | "day" | "all";
            /**
             * Agg
             * @enum {string}
             */
            agg: "mean" | "median" | "min" | "max" | "first" | "last" | "delta";
            /**
             * Group By
             * @enum {string}
             */
            group_by: "participant" | "cohort";
            /** Series */
            series: components["schemas"]["Series"][];
            /** Total Series */
            total_series: number;
            /** Truncated */
            truncated: boolean;
        };
        /**
         * QuerySpec
         * @description A generic question to the data: which metrics, whose, when, how reduced.
         */
        QuerySpec: {
            /** Metrics */
            metrics?: string[];
            /** Participants */
            participants?: string[] | null;
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /** Hours */
            hours?: number | null;
            /**
             * Bucket
             * @default hour
             * @enum {string}
             */
            bucket?: "raw" | "hour" | "day" | "all";
            /**
             * Agg
             * @default mean
             * @enum {string}
             */
            agg?: "mean" | "median" | "min" | "max" | "first" | "last" | "delta";
            /**
             * Group By
             * @default participant
             * @enum {string}
             */
            group_by?: "participant" | "cohort";
            /** Sort By */
            sort_by?: string | null;
            /**
             * Order
             * @default desc
             * @enum {string}
             */
            order?: "asc" | "desc";
            /** Limit */
            limit?: number | null;
        };
        /** Series */
        Series: {
            /** Participant Id */
            participant_id: string | null;
            /** Display Name */
            display_name: string;
            /** Points */
            points: {
                [key: string]: unknown;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WidgetData */
        WidgetData: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "trend" | "ranking" | "cohort_trend" | "stat" | "table" | "heatmap";
            query: components["schemas"]["QuerySpec"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            result: components["schemas"]["QueryResult"];
            /** Steps */
            steps: components["schemas"]["WidgetStep"][];
        };
        /** WidgetPreview */
        WidgetPreview: {
            result: components["schemas"]["QueryResult"];
            /** Steps */
            steps: components["schemas"]["WidgetStep"][];
        };
        /**
         * WidgetSpec
         * @description What a pin stores: enough to rebuild the widget at any later time.
         */
        WidgetSpec: {
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "trend" | "ranking" | "cohort_trend" | "stat" | "table" | "heatmap";
            query: components["schemas"]["QuerySpec"];
        };
        /** WidgetStep */
        WidgetStep: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "design" | "fetch" | "compliance" | "bind";
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_personas_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrincipalOut"][];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrincipalOut"];
                };
            };
        };
    };
    catalog_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    run_query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuerySpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    participants_participants_get: {
        parameters: {
            query?: {
                sort_by?: string;
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    participant_participants__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_participants__person_id__explain_get: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_participants__person_id__compare_get: {
        parameters: {
            query: {
                metric: string;
            };
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CohortComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cohort_cohort_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CohortOverview"];
                };
            };
        };
    };
    clock_state_clock_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClockState"];
                };
            };
        };
    };
    control_clock_clock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClockCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClockState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_stream_get: {
        parameters: {
            query?: {
                interval?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_turn_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    threads_chat_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThread"][];
                };
            };
        };
    };
    thread_chat_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tools_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    list_widgets_widgets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinnedWidget"][];
                };
            };
        };
    };
    pin_widget_widgets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WidgetSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinnedWidget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_widget_widgets_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WidgetSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    widget_data_widgets__widget_id__data_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                widget_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpin_widget_widgets__widget_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                widget_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
